pipeline {
    agent any
    tools {
        maven "M2_HOME"
    }
 
    stages {

        

        
        



        stage("Maven Build") {
            steps {
                 dir('kaddem') {
                   sh "mvn package -DskipTests=true"
                }
                
            }
        }

           }
 }


